# A revised and optimized GitHub Actions workflow for a full Android build.
# This workflow includes steps for setting up the correct JDK, Android NDK,
# CMake, and Gradle, with caching enabled for faster execution times.

name: Full Auto Build (CMake, NDK, Gradle, JDK)

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "24"

      - name: Install Android NDK and CMake
        uses: android-actions/setup-android@v3
        with:
          components: "ndk;26.1.10909125 cmake;3.22.1"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build project
        run: ./gradlew build --stacktrace